@extends('layouts.app')
@section('title', 'Dashboard')
@section('content')

<video class="w-full" autoplay muted>
    <source src="public\videos\video.mp4" type="video/mp4">
    Your browser does not support the video tag.
</video>
Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet quos consequatur neque exercitationem maxime nemo. Ut obcaecati deserunt nisi iure! Autem, soluta voluptates nisi sint obcaecati enim, dolores deleniti ducimus veniam placeat totam laboriosam eum earum consequuntur dolorem sunt maxime corporis, perspiciatis adipisci dignissimos. Voluptatibus repellendus nisi repellat nobis quod quia molestias ab corrupti numquam tenetur, minus iste assumenda harum id quos at? Ad ipsa, quia dicta, amet nisi similique, veniam ducimus a officia asperiores temporibus pariatur fugiat est dolores cum corrupti error voluptatum suscipit. Eligendi tenetur aspernatur architecto, id hic odit incidunt blanditiis aliquam beatae, eaque earum qui. Hic quaerat alias, maxime sit harum quibusdam temporibus, enim quae quos doloribus ab repellat incidunt odit, deserunt aliquid ipsam? Cupiditate itaque saepe tempore, delectus totam fugit. In dolores magnam ea architecto quod voluptates iure. Ab nulla ea officiis aut soluta eum repellat fugit tenetur dolorem eligendi est sunt, consectetur animi, suscipit, saepe blanditiis tempora culpa eos! Dolor corporis totam id ut ab dicta soluta. Quaerat, sequi illo? Voluptatum ullam incidunt modi, odit magni ratione vitae architecto velit nulla deleniti optio veniam fugiat voluptatem maxime laborum cupiditate molestias ut sunt accusantium earum consectetur vel. Eius voluptatem dolores accusantium, aut tempora quam excepturi veniam fugit fuga nostrum rerum cum maiores architecto beatae eos ratione ducimus doloremque culpa nulla sint amet debitis consequatur explicabo aperiam. Fugit quam blanditiis reprehenderit iure qui aspernatur quaerat nihil culpa, beatae sequi impedit animi. Tempore necessitatibus, porro aspernatur doloremque amet odio dolore eligendi assumenda sint molestiae? Veritatis, fuga molestias.
@endsection